### PR TITLE
added guidelines for flight planning

### PR DESCRIPTION
**Pull request by bjorn-stevens**

### CODE REVIEW

**Comment by bjorn-stevens** [comment]
I wasn't sure about where and how to put this in the doctored... or how the header information should be included in the markdown, but hopefully this creates something that can be amended and included with minimal effort

**Comment by lkluft** [comment]
> I wasn't sure about where and how to put this in the doctored... 

I moved it to `orcestra_book/plans/howto.md`. This way, the official URL will be http://orcestra-campaign.org/plans/howto which is simply nice to read.

> or how the header information should be included in the markdown, 

We only need the `orphan: true` settings which tells Sphinx to not worry about the fact that the document is not included in the table of contents; we do reference it manually.

> but hopefully this creates something that can be amended and included with minimal effort

Technically, it is included now 👍 If Cathy is fine with the content, we can merge

**Review by lkluft — APPROVED** [review]

**Comment by chohenegger** [comment]
One thing that was not clear to me was if this was a description of the flightplan for the pilot, or for the information we need to give FX (which e.g. follows a different way to write lat/lon) or for the flightplan we put on internet. Shouldn't we describe all the steps? Or are there somewhere else.
Also, I saw that the day before often meant 10, at least for ATC

**Comment by chohenegger** [comment]
@bjorn-stevens the coordinates are written in the wrong way for the pilot

**Comment by bjorn-stevens** [comment]
Checked with Cathy, this is now ready.

**Pull request merged**
