### PR TITLE
Adding the schedule of the seminars

### LINKED ISSUE #182: Science seminars on the website
It would be super nice to have an overview of all the (planned) science seminars somewhere on the website :)

### PR DESCRIPTION
**Pull request by yu71ng**
This would close #182.

### CODE REVIEW

**Comment by lkluft** [comment]
Is the operation page the right place for this? Somehow we put everything there and leave the other sections as wasteland...

**Comment by lkluft** [comment]
Maybe we could place it under the "Science" section 😉

**Comment by yu71ng** [comment]
Where would it fit better than? I thought since `operation` is the place-to-go during the campaign, why not having all the current and on-going events on the same page?

But I am open for suggestions.

**Comment by yu71ng** [comment]
> Maybe we could place it under the "Science" section 😉

But didn't you suggested to remove the Science section? (#184)

**Comment by yu71ng** [comment]
> > > Maybe we could place it under the "Science" section 😉
> > 
> > 
> > But didn't you suggested to remove the Science section? (#184)
> 
> We could replace the current science page with the schedule for the science seminar ☺️ This way, we would advertise the science that is happening during ORCESTRA

Is that science happening during ORCESTRA though? So far it is scientists talking about their research back home, no? 
In general, I don't mind, we can do that 🤷🏻‍♀️

**Comment by lkluft** [comment]
> > > > Maybe we could place it under the "Science" section 😉
> > > 
> > > 
> > > But didn't you suggested to remove the Science section? (#184)
> > 
> > 
> > We could replace the current science page with the schedule for the science seminar ☺️ This way, we would advertise the science that is happening during ORCESTRA
> 
> Is that science happening during ORCESTRA though? So far it is scientists talking about their research back home, no? In general, I don't mind, we can do that 🤷🏻‍♀️

I hoped so 🤷‍♂️ Otherwise it feels weird to have this seminar as part of our campaign schedule 😉 But maybe @JuliaWindmiller1987 can chime in here

**Comment by lkluft** [comment]
LGTM 🚀

**Pull request merged**
