### PR TITLE
HALO-20240903a: use FlightPlan object

### PR DESCRIPTION
**Pull request by d70-t**
This change makes use of https://github.com/orcestra-campaign/pyorcestra/pull/60 and https://github.com/orcestra-campaign/pyorcestra/pull/62, thus it **should not be merged** before  a new version of pyorcestra with the respective functionality is released.

The main change is the automatic export of the flight plan to TXT, based on the actual definition of the flight plan. In order to achieve this, all the information of the flight plan had to be collected in a new `FlightPlan` object, which should be used from now on instead of either the waypoint lists or the expanded dataset.

### CODE REVIEW

**Comment by d70-t** [comment]
The newest change also depends on https://github.com/orcestra-campaign/pyorcestra/pull/63, to simplify the computation of points on the EarthCARE track.

**Review by bjorn-stevens — COMMENTED** [review]
This looks great, see my comment on [PR 60](https://github.com/orcestra-campaign/pyorcestra/pull/60) in the pyorcestra for my plan to incorporate these changes

**Comment by lkluft** [comment]
The infrastructure is set now. All new flight planning exports can be used for the official builds.

**Comment by bjorn-stevens** [comment]
I suggest that we close this when we close PR #320 which incorporates these changes

**Comment by bjorn-stevens** [comment]
Closing as #320 looks ready to merge... will reopen if it doesn't.

**Pull request closed without merging**
