### PR TITLE
Added markdown on the role of docu-sci.

### PR DESCRIPTION
**Pull request by bjorn-stevens**
this is a rough draft, but good to review. @lkluft maybe think bout a home... in the meantime I hope Basile can review it.

### CODE REVIEW

**Comment by lkluft** [comment]
> [...] @lkluft maybe think bout a home... in the meantime I hope Basile can review it.

I am not 100% sure about the target audience yet. This could go directly into the flight planning tutorial to remind the flight PI of the documentation scientist's role in selecting and briefing them. Alternatively, we could link it as an info box on the HALO operations page (just like the planning tutorial).

**Comment by bjorn-stevens** [comment]
I'll give this another read  before merging...  so  it is okay to let it linger till I say otherwise.

**Comment by d70-t** [comment]
> I'll give this another read  before merging...  so  it is okay to let it linger till I say otherwise.

For cases like these, I'd recommend to convert the pull request into a draft pull request. This will prevent accidental merging and shows that someone still wants to read over it, but also wants the PR to be open for discussion in the meantime.

**Comment by bjorn-stevens** [comment]
I thought that this could best be integrated in the same note box that we use for the how-to for flight plannings, i.e., something like the following:

How-To 
- for mission PI and flight planning
- for documentation scientist

**Pull request merged**
