### PR TITLE
Added KT19 quicklooks 

### PR DESCRIPTION
**Pull request by MichaelSchaeferLIM**

### CODE REVIEW

**Comment by bjorn-stevens** [comment]
Hi Michael, when I took this from your fork and tried to build it it said the figures were not included, at least I could not find: 
```bash
/Users/m219063/Research/Projects/ORCESTRA/book/orcestra_book/reports/HALO-20240825a.md:: WARNING: image file not readable: figures/HALO-20240825a/HALO_20240825a_KT-19.png
/Users/m219063/Research/Projects/ORCESTRA/book/orcestra_book/reports/HALO-20240829a.md:: WARNING: image file not readable: figures/HALO-20240829a/HALO_20240829a_KT-19.png
/Users/m219063/Research/Projects/ORCESTRA/book/orcestra_book/reports/HALO-20240831a.md:: WARNING: image file not readable: figures/HALO-20240831a/HALO_20240831a_KT-19.png
/Users/m219063/Research/Projects/ORCESTRA/book/orcestra_book/reports/HALO-20240903a.md:: WARNING: image file not readable: figures/HALO-20240903a/HALO_20240903a_KT-19.png
l```

**Comment by d70-t** [comment]
Apparently, there's a typo in the file names.

**Comment by bjorn-stevens** [comment]
So I think I resolved the conflicts, but for some reason when I download and try to build your branch I still miss the files indicated above.  I see that they were added, but somehow they don't appear when I  pull from your fork.  Maybe ping @lkluft to see if he has ideas..

**Comment by bjorn-stevens** [comment]
now I see it.. I'll get it.

**Pull request merged**
