### PR TITLE
Make takeoff/landing explicitly UTC

### PR DESCRIPTION
**Pull request by lkluft**
This PR:
* adds an explicit time zone (UTC) to all takeoff and landing times
* adds information about departure and arrival airports
* makes the takeoff validation for Sal International Airport more robust

### CODE REVIEW

**Comment by lkluft** [comment]
@mckimb could you check that I didn't mess with the ATR plans?

**Comment by yu71ng** [comment]
Should we maybe state somewhere for the flight plans that says "Time is in UTC". 
At least until #96 and #98 are still on-hold?

**Comment by lkluft** [comment]
> Should we maybe state somewhere for the flight plans that says "Time is in UTC". At least until #96 and #98 are still on-hold?

#96 is obsolete because it is handled in a cleaner way in this PR.

#98 might be a slightly different scope, because it allows to use thing different than UTC. Maybe this PR will also solve this, but we would need some input from a PI or someone working on flight planning ☺️

**Review by yu71ng — APPROVED** [review]
Good idea with adding the airport localities in case we want to add LT. :blush:

Times for the HALO flights seems right so far.

**Pull request merged**
