### PR TITLE
CELLO updates: add King Air flight plans to operations and misc.

### PR DESCRIPTION
**Pull request by tim-carlsen**
Add King Air to operations, add flight plan KA-20240815a, update cello.md and viual_campaign.md and coordination.md with some details for CELLO

### CODE REVIEW

**Comment by yu71ng** [comment]
Thanks to @tim-carlsen for this contribution!

Unfortunately, it encountered some problems when building the book, which I am not sure to identify. So I am asking @lkluft for a review, as I am not too experienced with git myself...

**Review by lkluft — COMMENTED** [review]
Hi Tim,
thanks for your contribution! Your chances are already perfectly in line with our infrastructure, thanks for this 👌 There is just a minor with adding the King Air to our automated overview. This part is a bit more hidden in the Sphinx infrastructure, so I am happy to make the necessary changes and push them to your PR

**Comment by tim-carlsen** [comment]
Hi Lukas, thanks a lot! Is there anything I still need to do once you pushed them to my PR (e.g. making a new pull request)? Sorry, I'm still a bit new to git :)

**Comment by lkluft** [comment]
> Hi Lukas, thanks a lot! Is there anything I still need to do once you pushed them to my PR (e.g. making a new pull request)? Sorry, I'm still a bit new to git :)

No worries, there is nothing you need to do ☺️ The only thing you should avoid is pushing new changes to your `main` branch in between, because you have opened your PR from `main`. In the future, you should create a dedicated [branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) for individual features; this would allow us to go back and forth on that branch, while giving you the flexibility to do other things on main/other branches.

**Comment by tim-carlsen** [comment]
Ah ok good to know. I changed stuff on a different branch, but once I could build the book locally I merged it with my local main and then pushed it. But I can push the branch directly from now on, sorry about that!

**Comment by lkluft** [comment]
I couldn't commit my changes because the `main' branches are protected from users (another reason for feature branches 😉).

I opened #144, which contains your changes and my updates. Basically, I added the infrastructure to create a King Air overview table, and reduced the image size so as not to bloat the repository.

**Comment by lkluft** [comment]
If the two of you are fine with the changes there, we can merge the other PR (the one here will be closed automatically) ☺️

**Pull request closed without merging**
