### PR TITLE
New suggestion for profile plot

### PR DESCRIPTION
**Pull request by bjorn-stevens**
This new formatting of the profile plot is offered for discussion.

- is it improved and more helpful?
- if so is it better to be included in the flight planning so the flight planners see how to use the plan, or is it better to be put as a function in pyorcestra
- if put in pyorcestra do we run the risk of making that over elaborated.

### CODE REVIEW

**Comment by bjorn-stevens** [comment]
unfortunately I built this on top of the new flight plan which fails to build... and for those who cannot build the book and see the difference, here is the new profile plot:

profile

and here is the python code:

```python
import matplotlib.pylab as plt
import pandas as pd
import seaborn as sns

path  = plan.ds
ftime = [f"{x:%H:%M}" for x in pd.to_datetime(path.time[path.waypoint_indices])]

fig, ax = plt.subplots(figsize=(15, 6))
sns.despine(offset=10)

secax = ax.secondary_xaxis("top")
secax.set_xlabel("waypoints")
secax.set_xticks(
    path.time[path.waypoint_indices],
    path.waypoint_labels.values,
    rotation="vertical",
)

ax.set_xticks(path.time[path.waypoint_indices],labels=ftime,rotation=60.)
ax.set_yticks([200,350,410,450])
ax.set_xlabel("Time / UTC")
ax.set_ylabel("Flight Level / hundreds of feet")

ax.plot(path.time, path.fl, color="dodgerblue", lw=2)
```

**Comment by chohenegger** [comment]
Definitely more insightful than the previous version :) As a small comment, I would do the line orange as we tend to do flight track in orange.
For a "python dummy" like me, functions are too elaborate and then I don't know how to use them. I would prefer it in the flight plan and more explicit so that I can somehow guess how things work and how to use/adapt it if needed.

**Comment by lkluft** [comment]
I think the changes improve the overall look of the vertical profile 👍. 

In terms of implementation, I have a tendency to create a convenience function for this. In my opinion, understanding the number of lines of code is a bigger hurdle for new flight planners than a predefined function with a nice docstring and user parameters. But I never planned a flight, so others might chime in here 😉

**Comment by d70-t** [comment]
Sorry for being a bit late in here.
The plot seems to be better than what we've got currently. My suggestion would be to replace the current version of `vertical_preview` in pyorcestra (in the `flightplan` module). This will then eventually bubble up as the new default in our flight plans.

I'd just ensure that the color of the line stays consistent (e.g currently I guess we're using `C1` as the default color for aircraft trajectories).

**Comment by lkluft** [comment]
Is this still being discussed, developed, or on hold?

**Comment by bjorn-stevens** [comment]
It is just waiting a few minutes of my time.. hopefully soon, but thanks very much for checking.

**Comment by bjorn-stevens** [comment]
This is now a PR in the pyorcestra book which can be found [on the pyorcestra pages as PR 78](https://github.com/orcestra-campaign/pyorcestra/pull/78).  Hence closing.

**Pull request closed without merging**
